variable "name" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_capacity" {}
variable "health_check_grace_period" {}
variable "health_check_type" {}
variable "force_delete" {}
variable "target_group_arns" {}
variable "vpc_zone_identifier" {}
variable "launch_template_id" {}
variable "launch_template_version" {}